name: TeiloChat
version: ${jenkins.buildNumber}
main: org.elliotnash.teilochat.paper.TeiloChat
api-version: 1.16
authors: [Elliot Nash]
description: Chat customization plugin for spigot
website: elliotnash.org
commands:
  teilochat:
    aliases: tc
permissions:
  teilochat.other:
    description: lets a player set someone elses name / message prefix
    default: op